server:
  port: 9090
spring:
 datasource:
  url: jdbc:h2:mem:testdb  
  driverClassName: org.h2.Driver  
  username: sa  
  password: sa
 profiles:
  active: development
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  show-sql: true
 h2:
  console:
   enabled: true
 data:
  jpa:
   repositories:
    bootstrap-mode: default